### ISSUE TITLE
Initialize FireStore Remote

### ISSUE THREAD

**Issue by don1197** [CMPUT301F19T24/GroupProject#3]
- TBD

**Comment by eightysixth** [comment]
Remote initialized. Updated build.gradle files and credentials config file included in app source code.
Structure:
![moodEvents collection](https://user-images.githubusercontent.com/25541207/68178850-aefd2800-ff4a-11e9-8079-bd53294ccd2f.png)
![relationships collection](https://user-images.githubusercontent.com/25541207/68178882-cd632380-ff4a-11e9-8999-0da150f24962.png)
![users list](https://user-images.githubusercontent.com/25541207/68178901-da801280-ff4a-11e9-8f90-3593e22dcd73.png)
![document storage](https://user-images.githubusercontent.com/25541207/68178932-fb486800-ff4a-11e9-8c97-abc9b3bfbe3d.png)
