### ISSUE TITLE
XML Files

### ISSUE THREAD

**Issue by riona-wiberg** [CMPUT301F19T24/GroupProject#8]
- Turn UI mockups into XML files
- string.xml rather than hardcoding data!

**Comment by don1197** [comment]
Tasks Completed:
- Created view for moodEvents, as shown in mocked up models
- Created view for detailed moodEvents, as shown in mocked up models
- Uploaded demo emoticons for base sub-moods.
- Defined colors for each sub-moods
- Created demo to showcase the above-mentioned features above.

**Comment by don1197** [comment]
Tasks Completed:
- Sorting by Mood Name, and Timestamp
- Defined Social Situation as Enum

**Comment by eightysixth** [comment]
Tasks completed:
XML Files to display tabbed list, users in a list, requests in a list
